version: 2.1

workflows:
  build:
    jobs:
      - build

jobs:
  build:

    working_directory: ~/repo

    # docker hub images https://hub.docker.com/
    docker:
      - image: cimg/ruby:3.1.4-node
        environment:
          TZ: "UTC"
    resource_class: small

    steps:
      - checkout

      - run:
          name: Ruby dependencies
          command: bundle check || bundle install


      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      
      - run:
          name: Firebase Setup
          command: npm install firebase-tools --unsafe-perm

      - run:
          name: Deploy Site
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_API_TOKEN"